mod 'puppet/extlib', '0.11.3'
mod 'puppetlabs/apache', '1.10.0'
mod 'puppetlabs/apt', '2.2.1'
mod 'puppetlabs/concat', '2.1.0'
mod 'puppetlabs/firewall', '1.7.2'
mod 'puppetlabs/inifile', '1.4.3'
mod 'puppetlabs/postgresql', '4.7.1'
mod 'puppetlabs/stdlib', '4.11.0'
mod 'theforeman/foreman', git: 'https://github.com/theforeman/puppet-foreman'
mod 'theforeman/foreman_proxy', git: 'https://github.com/theforeman/puppet-foreman_proxy'
mod 'theforeman/puppet', '4.3.2'
mod 'theforeman/tftp', '1.8.0'
